version: "3.8"

services:
  TwilioVoiceEcho:
    build:
      context: .
      dockerfile: dockerfiles/twiliovoiceecho.dockerfile
    command: >
      -m app.main
      --bind_address "${BIND_ADDRESS}"
      --ws_host "${WS_ADDRESS}"
      --max_call_time "${MAX_CALL_DURATION}"
    image: twilio_voice_echo
    network_mode: "host"
    restart: "always"
